### ISSUE TITLE
[BUG] Attachment uploads and Comments not working

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator-frontend#255] opened 2024-07-19 07:59 UTC
**Describe the bug**
Responding to a request with an attachment does not record the message.
UI: v1.4.2
Application: v3.6.1

**How to reproduce**

1.     write a text in the response
2.     attach the file
3.     select Everyone
4.     Send message

**What happens**
Nothing goes into the message.

**What should happen**
Messages are recorded and shown, attachments are uploaded and shown.

**Comment by iblanque** [comment] 2024-07-24 14:25
Attachments in forms in negotiations are not working either. 
- Frontend version: 1.5.2 (docker tag 1.5)
- Element of type "FILE" marked as "required"
- The Frontend shows a message "Please fill out all required fields correctly" and it does not progress.
- The attachment is not uploaded and there is no error message in the logs of the frontend or the backend.

**Comment by RadovanTomik** [comment] 2024-07-24 15:02
Managed to reproduce it locally. @tmilost can you fix it? Should be relatively easy. The bug is caused by marking a field of type file as required. The frontend does not register that the file for that field was added.

**Closed** 2024-08-02 08:33 UTC
Labels: bug
